name: Compile Source
on: 
  push:
    branches:
      - release
jobs:
  compile:
    runs-on: ubuntu-latest
    name: Make Executable
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master  

    - name: Make 
      run: make

    - run: ls -la
    
    - uses: actions/upload-artifact@v3
      with:
        name: snake
        path: snake